# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fafadia Tech's Official Blog
email: customercare@fafadiatech.com
description: > # this means to ignore newlines until "baseurl:"
  Fafadia Tech is a Mumbai based Startup focusing on open source technologies like Python, PHP and Linux. We also work on Big Data, Machine Learning and Natural Language Process. Our team is currently 18+ people strong. We've been in business since 2009. This blog is collection of our writing, experiments and thoughts. In Python we specially like Django, Flask and Tornado frameworks. For frontend we use Bootstrap and AngularJS. We've developed few Android and iOS Applications. Till date we've successfull completed 60+ projects in Health Care, eCommerce and Finance.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://fafadiatech.github.io" # the base hostname & protocol for your site
twitter_username: fafadiatechhq
github_username:  fafadiatech

# Build settings
markdown: kramdown
